export declare const getListConversationsQueryKey: () => string[];
export declare const getGetConversationQueryKey: (id: number) => (string | number)[];
export declare const getGetMessagesQueryKey: (conversationId: number) => (string | number)[];
export declare const getListNotificationsQueryKey: () => string[];
export declare const getListModulesQueryKey: () => string[];
export declare const getListPublicModulesQueryKey: () => string[];
export declare const getListAdCampaignsQueryKey: () => string[];
export declare const getAdminListAdCampaignsQueryKey: () => string[];
export declare const getListNotesQueryKey: () => string[];
export declare const getGetNoteQueryKey: (id: number) => (string | number)[];
export declare const getListTestsQueryKey: () => string[];
export declare const getGetModuleSourcesQueryKey: (id: number) => (string | number)[];
export declare const getGetModuleContentQueryKey: (id: number) => (string | number)[];
export declare const getGetOrgQueryKey: () => string[];
export declare const getListOrgMembersQueryKey: () => string[];
export declare const getListExpertQueueQueryKey: () => string[];
export declare const getGetMeQueryKey: () => string[];
export declare const getGetCreditsBalanceQueryKey: () => string[];
export declare const getGetBufferModeQueryKey: () => string[];
export declare const getListCreditTransactionsQueryKey: () => string[];
export declare function useGetMe(options?: any): any;
export declare function useUpdateMe(options?: any): any;
export declare function useCompleteOnboarding(options?: any): any;
export declare function useGetCreditsBalance(options?: any): any;
export declare function useListCreditTransactions(options?: any): any;
export declare function useGetBufferMode(options?: any): any;
export declare function useUpdateBufferMode(options?: any): any;
export declare function useListConversations(options?: any): any;
export declare function useGetConversation(id: number, options?: any): any;
export declare function useGetMessages(conversationId: number, options?: any): any;
export declare function useCreateConversation(options?: any): any;
export declare function useDeleteConversation(options?: any): any;
export declare function useUpdateConversation(options?: any): any;
export declare function useSendMessage(options?: any): any;
export declare function useListNotifications(options?: any): any;
export declare function useMarkAllNotificationsRead(options?: any): any;
export declare function useListModules(params?: any, options?: any): any;
export declare function useListPublicModules(params?: any, options?: any): any;
export declare function useGetModule(id: number, options?: any): any;
export declare function useCreateModule(options?: any): any;
export declare function useDeleteModule(options?: any): any;
export declare function usePublishModule(options?: any): any;
export declare function useStarModule(options?: any): any;
export declare function useGetModuleSources(id: number, options?: any): any;
export declare function useGetModuleContent(id: number, options?: any): any;
export declare function useAddModuleSource(options?: any): any;
export declare function useListAdCampaigns(options?: any): any;
export declare function useRegisterAdBusiness(options?: any): any;
export declare function useCreateAdCampaign(options?: any): any;
export declare function useAdminListAdCampaigns(options?: any): any;
export declare function useApproveAdCampaign(options?: any): any;
export declare function useRejectAdCampaign(options?: any): any;
export declare function useListNotes(options?: any): any;
export declare function useCreateNote(options?: any): any;
export declare function useUpdateNote(options?: any): any;
export declare function useDeleteNote(options?: any): any;
export declare function useListTests(options?: any): any;
export declare function useCreateTest(options?: any): any;
export declare function useGetTest(id: number, options?: any): any;
export declare function useDeleteTest(options?: any): any;
export declare function useSubmitTestAttempt(options?: any): any;
export declare function useGetDashboardSummary(options?: any): any;
export declare function useGetRecentActivity(options?: any): any;
export declare function useGetTrendingModules(options?: any): any;
export declare function useGetOrg(options?: any): any;
export declare function useCreateOrg(options?: any): any;
export declare function useListOrgMembers(options?: any): any;
export declare function useInviteOrgMember(options?: any): any;
export declare function useListWorkspaces(options?: any): any;
export declare function useSwitchWorkspace(options?: any): any;
export declare function useGetOrgAnalytics(params?: any, options?: any): any;
export declare function useListExpertQueue(params?: any, options?: any): any;
export declare function useReplyExpertTicket(options?: any): any;
export declare function useUpdateOrg(options?: any): any;
export declare function useDeleteOrg(options?: any): any;
export declare function useUpdateOrgMember(options?: any): any;
export declare function useRemoveOrgMember(options?: any): any;

export declare function useGetAIModels(options?: any): any;
export declare function useUpdateAIModel(options?: any): any;
export declare function useGetAIServices(options?: any): any;
export declare function useUpdateAIServiceModel(options?: any): any;
export declare function useGetAILogs(options?: any): any;
export declare function useClearAILogs(options?: any): any;
export declare function useGetAdminStats(options?: any): any;
export declare function useGetAdminUsers(options?: any): any;
export declare function useUpdateUserCredits(options?: any): any;
